### ISSUE TITLE
Port Makefile to Bakefile

### ISSUE THREAD

**Issue by dutradda** [dutradda/apidaora#2]
`bake` is a tool for automate commands workflows.

Has a `Bakefile` and it is similar with the `Makefile` syntax.

Info:
https://github.com/kennethreitz/bake

Acceptance Criteria:
- All commands must be ported (except help, that bake do it for us)

**Comment by armonge** [comment]
I'm working on this one :+1:

**Comment by dutradda** [comment]
@armonge
Great! Thank you!
