### ISSUE TITLE
Look like no longer maintained?

### ISSUE THREAD

**Issue by hstk30** [dutradda/apidaora#30]
Hi, I found the fastest Python Web Framework. But, seem no longer maintained? 
Or this Framework just for Performance competition？

**Comment by douglasfarinelli** [comment]
Hi @hstk30.

This project was created by @dutradda to really be productive.

Unfortunately @dutradda had to be off github for a while, but soon he will be bringing new features and fixes to the project.

Thanks!

**Comment by hstk30** [comment]
Thanks! I'm looking forward!
